name: Backend CI - GitOps

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: tapashranjannandi/expense-app-backend
  GITOPS_REPO: TAPASHRANJANNANDI/expense-tracker-fullstack-deployment
  TARGET_FILE: kubernetes/backend/deployment.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout application source
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Set Docker tag
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # 3️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t $DOCKER_IMAGE:${IMAGE_TAG} .
          docker tag $DOCKER_IMAGE:${IMAGE_TAG} $DOCKER_IMAGE:latest

      # 5️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push $DOCKER_IMAGE:${IMAGE_TAG}
          docker push $DOCKER_IMAGE:latest

      # 6️⃣ Checkout GitOps repo
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gitops

      # 7️⃣ Update image tag in GitOps repo
      - name: Update Kubernetes manifest
        run: |
          cd gitops

          sed -i "s|image: $DOCKER_IMAGE:.*|image: $DOCKER_IMAGE:${IMAGE_TAG}|" $TARGET_FILE

          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions CI"

          git add $TARGET_FILE
          git commit -m "ci: update backend image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push
